name: Main

on:
  push:
    branches:
      - master
      - feature/*

  pull_request:
    branches:
      - master

  schedule:
    - cron: "0 8 * * *"

jobs:
  examples-shell:
    strategy:
      matrix:
        runs-on:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Nix
        uses: nixbuild/nix-quick-install-action@v9

      - run: nix-build -v examples/standard/default.nix

  examples-flake:
    strategy:
      matrix:
        runs-on:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Nix
        uses: nixbuild/nix-quick-install-action@v9
        with:
          nix_conf: |
            extra-experimental-features = nix-command flakes

      - run: |
          nix -vL build --impure ./examples/flake --override-input opam-nix-integration path:./.
